### ISSUE TITLE
Logo size

### ISSUE THREAD

**Issue by akbarjondev** [Islombek9717/planet_x#1]
In your index.html website logo has not  width and height

![Screenshot from 2021-08-16 16-52-08](https://user-images.githubusercontent.com/36984628/130638173-b105d583-c290-41d4-95ef-4603b664e9a4.png)

**Fix it right now**

**Comment by akbarjondev** [comment]
Test comment

**Comment by Islombek9717** [comment]
Done 9666f995b7876bd3dcf8c2d4cbe04425c0a75ccc
